[theme]
primaryColor = "#7670E6"
backgroundColor = "#F1F1F1"
secondaryBackgroundColor = "#CCCCCC" 
textColor = "#000000"
font = "sans serif"

[server]
#serverAddress = "172.25.16.1"
#address = "192.168.254.11"
#port = 8501
